NumPy - Numerical Python
Advantages of Numpy Arrays:
  1. Allows several Mathematical Operations
  2. Faster operations

In [1]:
import numpy as np

In [2]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [3]:
# One Dimensional array 
a = np.array([1, 2, 3, 4, 5])
print(a)
print(a.shape)

[1 2 3 4 5]
(5,)


In [4]:
# Two Dimensional array 
b = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)])
print(b)
print(b.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [5]:
# Create array with all values are Zero
c = np.zeros((4, 5)) # 4 * 5 array (4 rows and 5 columns)  
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
# Create array with all values are Ones
d = np.ones((4, 5)) # 4 * 5 array (4 rows and 5 columns)  
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
# Create array with a particular value
d = np.full((4, 5), 10) # 4 * 5 array (4 rows and 5 columns) with all values are 10
print(d)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [8]:
# Create identity matrix 
e = np.eye(5) # 5 * 5 identity matrix
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
# Create a array with random element
f = np.random.random((4, 5)) # 4 * 5 array with random values
print(f)

[[0.7094888  0.23927357 0.12575008 0.29224042 0.71076733]
 [0.20544197 0.97071333 0.52613262 0.81498588 0.75214093]
 [0.21613422 0.32037617 0.586503   0.48211764 0.2088106 ]
 [0.63514565 0.07823533 0.99116766 0.83780798 0.36197921]]


In [10]:
# Create random integer values array
g = np.random.randint(1, 100, (4, 5)) # 4 * 5 array with random integer values between 1 and 100
print(g)

[[ 7 98 74 17 84]
 [95 37  4 21 24]
 [10 84 68 22  7]
 [ 5 17 29 36 84]]


In [11]:
# array shape
print(g.shape)
# array number of dimension 
print(g.ndim)
# number of elements in array
print(g.size)
# checking datatype values in the array
print(g.dtype)

(4, 5)
2
20
int64


In [12]:
# Mathematical operations on np array 
a = np.random.randint(10, 30, (3, 3))
b = np.random.randint(1, 10, (3, 3))
print(a)
print(b)

[[15 26 21]
 [21 22 25]
 [27 10 28]]
[[3 7 7]
 [3 8 3]
 [8 2 3]]


In [13]:
# addition 
print(a + b) # element wise addition 
print(np.add(a, b)) # element wise addition


# subtraction
print(a - b) # element wise subtraction
print(np.subtract(a, b)) # element wise subtraction


# multiplication
print(a * b) # element wise multiplication
print(np.multiply(a, b)) # element wise multiplication


# division
print(a / b) # element wise division
print(np.divide(a, b)) # element wise division

[[18 33 28]
 [24 30 28]
 [35 12 31]]
[[18 33 28]
 [24 30 28]
 [35 12 31]]
[[12 19 14]
 [18 14 22]
 [19  8 25]]
[[12 19 14]
 [18 14 22]
 [19  8 25]]
[[ 45 182 147]
 [ 63 176  75]
 [216  20  84]]
[[ 45 182 147]
 [ 63 176  75]
 [216  20  84]]
[[5.         3.71428571 3.        ]
 [7.         2.75       8.33333333]
 [3.375      5.         9.33333333]]
[[5.         3.71428571 3.        ]
 [7.         2.75       8.33333333]
 [3.375      5.         9.33333333]]


In [14]:
# square root
print(np.sqrt(a))

# exponentiation
print(np.exp(a))

[[3.87298335 5.09901951 4.58257569]
 [4.58257569 4.69041576 5.        ]
 [5.19615242 3.16227766 5.29150262]]
[[3.26901737e+06 1.95729609e+11 1.31881573e+09]
 [1.31881573e+09 3.58491285e+09 7.20048993e+10]
 [5.32048241e+11 2.20264658e+04 1.44625706e+12]]


In [15]:
# sin
print(np.sin(a))

# cos
print(np.cos(a))

# log
print(np.log(a))


[[ 0.65028784  0.76255845  0.83665564]
 [ 0.83665564 -0.00885131 -0.13235175]
 [ 0.95637593 -0.54402111  0.27090579]]
[[-0.75968791  0.64691932 -0.54772926]
 [-0.54772926 -0.99996083  0.99120281]
 [-0.29213881 -0.83907153 -0.96260587]]
[[2.7080502  3.25809654 3.04452244]
 [3.04452244 3.09104245 3.21887582]
 [3.29583687 2.30258509 3.33220451]]


In [16]:
# dot product
print(np.dot(a, b))

# matrix multiplication
print(np.matmul(a, b))

# transpose
trans = np.transpose(a)
print(trans)
print(a.T) # another method 

[[291 355 246]
 [329 373 288]
 [335 325 303]]
[[291 355 246]
 [329 373 288]
 [335 325 303]]
[[15 21 27]
 [26 22 10]
 [21 25 28]]
[[15 21 27]
 [26 22 10]
 [21 25 28]]


In [17]:
# sum of all elements
print(np.sum(a))

# sum of each column
print(np.sum(a, axis=0))

# sum of each row
print(np.sum(a, axis=1))

# mean of all elements
print(np.mean(a))

# mean of each column
print(np.mean(a, axis=0))

# mean of each row
print(np.mean(a, axis=1))

# median of all elements
print(np.median(a))

# median of each column
print(np.median(a, axis=0))

# median of each row
print(np.median(a, axis=1))

# maximum of all elements
print(np.max(a))

# maximum of each column
print(np.max(a, axis=0))

# maximum of each row
print(np.max(a, axis=1))

# minimum of all elements
print(np.min(a))

# minimum of each column
print(np.min(a, axis=0))

# minimum of each row
print(np.min(a, axis=1))

195
[63 58 74]
[62 68 65]
21.666666666666668
[21.         19.33333333 24.66666667]
[20.66666667 22.66666667 21.66666667]
22.0
[21. 22. 25.]
[21. 22. 27.]
28
[27 26 28]
[26 25 28]
10
[15 10 21]
[15 21 10]


In [18]:
# sort
print(np.sort(a))

[[15 21 26]
 [21 22 25]
 [10 27 28]]


In [19]:
# reshape array
a = np.random.randint(10, 100, (4, 5))
print(a)
print(a.shape)
b = a.reshape(5, 4)
print(b)
print(b.shape)

[[26 82 10 14 98]
 [23 77 27 43 28]
 [71 46 59 48 66]
 [94 70 40 60 18]]
(4, 5)
[[26 82 10 14]
 [98 23 77 27]
 [43 28 71 46]
 [59 48 66 94]
 [70 40 60 18]]
(5, 4)
